# Generated by Django 4.2 on 2023-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_tag_uniq_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
