# Generated by Django 4.2 on 2023-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tag_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="uniq_id",
        ),
    ]
