# Generated by Django 4.2 on 2023-05-14 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
